### ISSUE TITLE
Build FTUE Splash screens

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4584]
### Your use case

When the app opens, and the user is not logged in, we show a Splash screen. 
- [_link to Figma splash screens_](https://www.figma.com/file/xdV4PuI3DlzA1EiBvbrggz/Login-Flow-v2?node-id=1628%3A31003)

**The Splash screens include:**
- ~A loading page~ Descoped 
- A landing page carousel that automatically rotates 4 images + text combinations every 5 seconds. The user can also swipe between screens. Once a user has manually swiped, the automatic transitions are disabled.
- 2 buttons, Get Started (create new account) & I already have an account (login)
  - While we are still building the FTUE experience Get Started will lead to … and I already have an account will lead to...

--- 
**Tasks**
- [x] Jordan to review the visuals used on screen
- [ ] Marketing to approve the copy used on screens
- Build
  - [x] I already have an account #4668 
  - [x] Carousel with 4 images, text combinations, I already have an account flow #4727 
  - [x] Automatic carousel rotation #4740
  - [x] Disable automatic carousel rotation after user interaction #4914 
  - [x] Update with final images/copy/dark mode gradients, styled title full stops #4880 
  - [x] Locking phones to portrait during FTUE auth #4918 
  - [ ] Enable feature #4964 
- [x] Design review before merge

---
_This issue is considered complete when the tasks are complete, the screen matches the Figma design, it's been reviewed (by Product, Design & Engineering), and merged._

**Comment by daniellekirkwood** [comment]
I'm testing something. Please ignore.

<img width="763" alt="Screenshot 2022-02-16 at 16 05 39" src="https://user-images.githubusercontent.com/89144281/154306382-4145b7ff-e3a9-4ed1-9cc9-dce595a33f4c.png">
