### ISSUE TITLE
[App Board Epic] Build a new onboarding experience 

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4586]
## For more information and updates see [Project Board](https://github.com/orgs/vector-im/projects/31/views/5) and [Epic](https://github.com/vector-im/element-meta/issues/146)

<hr>

The Below will not be updated.

### Your use case

This issue is an Epic to track the build of the new onboarding experience for iOS users.
This will only be available to iOS13 and above due to SwiftUI being available from iOS13 onwards.

---
### Design
- [x] Design Prototype for Create Account flow
- [x] Design Prototype for Sign in flow
- [x] Design Prototype for Password Recovery flow

[Figma](https://www.figma.com/file/xdV4PuI3DlzA1EiBvbrggz/Login-Flow-v2?node-id=2523%3A42803)

### Product
- [x] Prototypes reviewed by DACI

---
### Develop
**Create Account Flow**
- [x] #4584
- [x] #4585
- [x] https://github.com/vector-im/element-meta/issues/126
- [x] https://github.com/vector-im/element-meta/issues/127
- [x] https://github.com/vector-im/element-meta/issues/128
- [x] https://github.com/vector-im/element-meta/issues/129
- [x] https://github.com/vector-im/element-meta/issues/130
- [x] https://github.com/vector-im/element-meta/issues/131
- [x] https://github.com/vector-im/element-meta/issues/132
- [x] https://github.com/vector-im/element-meta/issues/133

**Sign in Flow**
- [x] https://github.com/vector-im/element-meta/issues/134

**Password Recovery Flow**
- [x] https://github.com/vector-im/element-meta/issues/135

**Other**
- [x] https://github.com/vector-im/element-meta/issues/136

**Comment by daniellekirkwood** [comment]
Discussion today: January 10, 2022

- Lock phone to portrait during onboarding
- Disable automatic carousel transitions when a page is manually selected
- Apply the use case selection as a posthog identity property
 - Need to agree on schema and naming for these
