### ISSUE TITLE
[Release] Element Android v1.3.15 - Corrective release

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#4970]
### Release checklist

This is a corrective release and it will contain:
- [x] Crash fixed in #4966
- [x] Crash fixed in #4962 
- [x] A fix for #4796 - jitpack [is confused again](https://jitpack.io/com/github/BillCarsonFr/JsonViewer/0.8/build.log), we will import the source in a module in this project. -> @bmarty 
- [x] A fix for #4969 -> @ouchadam 
- [ ] Other?

Please base your PRs on branch `hotfix/1.3.15`

<del>The App the SDK and the sample will be released.</del> Only the app will be released, no change in the SDK.

### Before the release

No Weblate sync

### Do the release

- [x] Create hotfix with gitflow, branch name `hotfix/1.3.15`
- [x] Change version to 1.3.15 (app and SDK)
- [x] Check the crashes from the PlayStore
- [x] Check the rageshake with the current dev version: https://github.com/matrix-org/element-android-rageshakes/labels/1.3.15-dev
- [ ] Run the integration test, and especially `UiAllScreensSanityTest.allScreensTest()`
- [ ] Create an account on matrix.org
- [x] Run towncrier: `towncrier --version v1.3.15 --draft` (remove `--draft` do write the file CHANGES.md)
- [x] Add file for fastlane under ./fastlane/metadata/android/en-US/changelogs
- [ ] Push the branch and start a draft PR (will not be merged), to check that the CI is happy with all the changes.
- [ ] Finish release with gitflow, delete the draft PR
- [x] Push `main` and the new tag `v1.3.15` to origin
- [x] Checkout `develop`
- [ ] Increase version in `./vector/build.gradle`
- [ ] Change the value of SDK_VERSION in the file `./matrix-sdk-android/build.gradle`
- [x] Commit and push `develop`
- [x] Wait for [Buildkite](https://buildkite.com/matrix-dot-org/element-android/builds?branch=main) to build the `main` branch.
- [x] Run the script `~/scripts/releaseElement.sh`. It will download the APKs from Buildkite check them and sign them.
- [ ] Install the APK on your phone to check that the upgrade went well (no init sync, etc.)
- [x] Create a new beta release on the GooglePlay console and upload the 4 signed Apks.
- [x] Check that the version codes are correct
- [x] Copy the fastlane change to the GooglePlay console in the section en-GB.
- [x] Push to beta release to 100% of the users
- [x] Create the release on gitHub [from the tag](https://github.com/vector-im/element-android/tags), copy paste the block from the file CHANGES.md
- [x] Add the 4 signed APKs to the GitHub release
- [x] Ping the Android Internal room
- [x] Add an entry in the internal diary

### Once Live on PlayStore

- [ ] Ping the Android public room and update its topic

### After at least 2 days

- [ ] Check the [rageshakes](https://github.com/matrix-org/element-android-rageshakes/issues)
- [ ] Check the crash reports on the GooglePlay console
- [ ] Check the Android Element room for any reported issues on the new version
- [ ] If all is OK, push to production and notify Markus (Bubu) to release the F-Droid version
- [ ] Ping the Android public room and update its topic with the new available version
