### ISSUE TITLE
IA 1: Understand current IA

### ISSUE THREAD

**Issue by niquewoodhouse** [vector-im/element-android#5153]
### Objective

In order to create a more useful information architecture for Android, we need a comprehensive understanding of the current Android app's IA.  

**Tasks**

- [x] Artefact: A map of the current Android Element IA
- [x] Gather already captured insights: What do we currently know to be navigational issues?
- [x] Gather insights: What are people trying to accomplish and where?  What's their overall objective when using Element?

**Comment by bmarty** [comment]
This is the Android project here, not iOS :)
