### ISSUE TITLE
IA 1: Expectations

### ISSUE THREAD

**Issue by niquewoodhouse** [vector-im/element-android#5154]
### Objective

We appreciate that users are trying Element with pre-existing expectations of how to use the interface to achieve their goals.  This may come from [HIG](https://developer.apple.com/design/human-interface-guidelines/ios/overview/themes/), it may come from other products they've previously used to achieve their goals, or other products they use for other goals.

The more we understand their pre-existing expectations, and respect them, the quicker we can help users discover what they want and find value in Element.

**Tasks**

- [ ] Artefacts: Competitor IA maps<sup>1</sup>
   - [ ]  Professional use (co-worker and teams)
     - [ ] Slack
     - [ ] Teams 
   - [ ]  Personal use (friends and family)
      - [ ] Whatsapp
      - [ ] Messages
      - [ ] Signal
   - [ ] Community use 
    - [ ] Discord   

<sup>1</sup> Each product mapped is not unique to a use case.
