### ISSUE TITLE
Mobile FTUE: Profile Personalisation screens (Android)

### ISSUE THREAD

**Issue by ouchadam** [vector-im/element-android#5200]
Android specific https://github.com/vector-im/element-meta/issues/132

- [x] Account created screen #5158 
- [x] Add support for additional homeserver capabilities (display name/avatar) #5208 
- [x] Choose a display name screen #5211
- [x] Add a profile picture screen #5323
- [x] Personalisation complete screen #5389
- [x] Avoid showing personalisation screens if the homeserver has disabled them #5375
- [x] Confirm error messaging and handling (local rules extracted to https://github.com/vector-im/element-meta/issues/204) #5517  
- [x] Enable feature - product/design sign off #5519 

Also:
- [ ] https://github.com/vector-im/element-meta/issues/132
- [x] https://github.com/vector-im/element-android/issues/5099
