### ISSUE TITLE
[Content] Amend spaces menu to have consistent copy

### ISSUE THREAD

**Issue by niquewoodhouse** [vector-im/element-android#5270]
Android is using different text and icons to iOS.  Design TBC, but will be limited to just changing some text and icons.

**Tasks**

- [ ] Change `List members` to `Members`
- [ ] Change `Leave space` to `Leave`
- [ ] Change explore rooms icon to be same as iOS

<img width="980" alt="image" src="https://user-images.githubusercontent.com/1587166/154952133-b34761ee-f055-46a3-b534-0a96b3eec6f9.png">

**Comment by bmarty** [comment]
In 1.4.6
