### ISSUE TITLE
Remove support for communities/groups

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#5733]
Communities have been deprecated so they should be removed from the app.

## Tasks

*   [x] ~~Estimate this issue~~
*   [x] ~~Announce to users who have communities enabled that they will be removed with the next release~~
*   [ ] Remove support for communities
*  [ ] Add copy for when a user tries to access a community (e.g. through a matrix.to link)
*   [ ] Compile a list of potential areas of the app that are touched as part of the coding work
*   [ ] Run a regression testing session to confirm that the removal of communities does not break anything else

## References

*   [Web task](https://github.com/vector-im/element-web/issues/17532)

**Comment by fedrunov** [comment]
groups will be disabled/removed from the backend in aprox. 3 weeks from now, so we don't have time to prepare a release with migration tool or announcement 

some entry points for groups will still present after removal (e.g. links in timeline) so we need somehow to inform user that feature was removed, e.g. via popup and we need design/description of how it should look like along with the string resources and images if necessary

**Comment by kittykat** [comment]
Copy to show when a user tries to open a community link:

> **This link is no longer supported.**  
> You're trying to open a link to a community (+community:matrix.org). Communities are no longer supported and have been replaced by spaces. [Learn more about spaces here.](https://element.io/blog/spaces-blast-out-of-beta/)

`+community:matrix.org` should be replaced by correct link  
  
\### References

Here is an example matrix.to link to a community: [https://develop.element.io/#/group/+community:matrix.org](https://develop.element.io/#/group/+community:matrix.org)

**Comment by kittykat** [comment]
@fedrunov Try this error message:
> Cannot open this link: communities are no longer supported and have been replaced by spaces.

**Comment by fedrunov** [comment]
After discussion with @kittykat it was decided that to be consistent with current link errors handling we should show just a toast message, instead of fullscreen error like on web. 

![Screenshot 2022-06-10 at 15 39 13](https://user-images.githubusercontent.com/66663241/173316701-36ba0dcb-6a5d-4c47-8863-d6e573a62396.png)

NOTE: default icon looks to be android's bug:

https://issuetracker.google.com/issues/202863198?pli=1
