### ISSUE TITLE
App Layout: Edit Layout [Android]

### ISSUE THREAD

**Issue by fedrunov** [vector-im/element-android#6502]
Android specific [https://github.com/vector-im/element-meta/issues/220](https://github.com/vector-im/element-meta/issues/220)

- [x] new fragment for room list #6611 
- [x] Recents list #6504
- [x] List filters #6505
- [x] Layout settings: #6506
- [x] move dialpad from bottom tabs #6787
- [x] remove bottom tabs at Home #6565
- [x] invites #6889
- [x] invites margin #6947
- [x] Invites Empty States #6876 
- [x] Home screen empty states #6835
- [x] change app settings #6646
- [x] Accessibility #6856 
- [ ] Tests #6509
- [x] Release experience #6909

Nice-to-have
- [x] scroll to start when new item added/moved #6776
- [x] Analytics #6508
- [x] #6770

**Comment by daniellekirkwood** [comment]
@fedrunov there's one remaining task in this epic - does it need to be done or are you happy that I close this out?
