### ISSUE TITLE
Delight: App Layout (Space Switching)

### ISSUE THREAD

**Issue by ericdecanini** [vector-im/element-android#6605]
This issue is the Android epic for https://github.com/vector-im/element-meta/issues/218

Enhancements:
- [x] https://github.com/vector-im/element-android/issues/6499
- [x] https://github.com/vector-im/element-android/issues/6580
- [x] https://github.com/vector-im/element-android/issues/6582
- [x] https://github.com/vector-im/element-android/issues/6752
- [x] https://github.com/vector-im/element-android/issues/6753
- [x] https://github.com/vector-im/element-android/issues/6717
- [x] https://github.com/vector-im/element-android/issues/6867
- [x] https://github.com/vector-im/element-android/issues/6859
- [x] https://github.com/vector-im/element-android/issues/6583
- [x] https://github.com/vector-im/element-android/issues/6754
- [ ] https://github.com/vector-im/element-android/issues/6756

Enhancements In PR:
- [x] https://github.com/vector-im/element-android/issues/6751
- [x] https://github.com/vector-im/element-android/issues/6815

Tasks:
- [x] https://github.com/vector-im/element-android/issues/6578
- [x] https://github.com/vector-im/element-android/issues/6483
- [ ] https://github.com/vector-im/element-android/issues/6484
- [ ] https://github.com/vector-im/element-android/issues/6755

Defects:
- [x] https://github.com/vector-im/element-android/issues/6850
- [x] https://github.com/vector-im/element-android/issues/6818
- [x] https://github.com/vector-im/element-android/issues/6767
- [x] https://github.com/vector-im/element-android/issues/6848
- [x] https://github.com/vector-im/element-android/issues/6750
- [x] https://github.com/vector-im/element-android/issues/6765
- [ ] https://github.com/vector-im/element-android/issues/6771
- [x] https://github.com/vector-im/element-android/issues/7011
- [ ] https://github.com/vector-im/element-android/issues/6858
- [ ] https://github.com/vector-im/element-android/issues/6950
